# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module
MOD = wave

# Source files (.c or .py)
#
SRC = voice.c wave_mod.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin, rv32imc)
# ARCH = armv7m

# won't help ...
# CFLAGS += -O3

# LDFLAGS += -lm
LINK_RUNTIME = 0

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
